/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cal */

#ifndef _Included_cal
#define _Included_cal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cal
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cal_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cal
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cal_sub
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cal
 * Method:    mul
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cal_mul
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cal
 * Method:    div
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cal_div
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cal
 * Method:    s
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_cal_s
  (JNIEnv *, jobject, jint);

/*
 * Class:     cal
 * Method:    c
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_cal_c
  (JNIEnv *, jobject, jint);

/*
 * Class:     cal
 * Method:    conc
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cal_conc
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
